updated

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -17,22 +17,26 @@ phases:
       # - echo "Listing Docker images"
       - docker image ls
       - ls -R
+      - cd community_images/nginx/bitnami
+      - echo "Running docker-compose up"
+      - docker-compose up -d
+      - docker ps -a
 
   post_build:
     commands:
 
-      - echo "Running the Docker container"
-      - CONTAINER_ID=$(docker run -d -p 80:80 rapidfort/nginx)
-      - echo "Copying the coverage script to the container"
-      - docker cp community_images/nginx/bitnami/coverage_script.sh $CONTAINER_ID:/coverage_script.sh
-      - echo "Running the script inside the container"
-      # - docker exec $CONTAINER_ID bash /coverage_script.sh
-      - |
-        if ! docker exec $CONTAINER_ID bash /coverage_script.sh; then
-          echo "Coverage script failed"
-          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
-                          --subject "Build Failed: NGINX Coverage Script" \
-                          --message "The coverage script failed to execute. Check the logs for details."
-          exit 1
-        fi
+      # - echo "Running the Docker container"
+      # - CONTAINER_ID=$(docker run -d -p 80:80 rapidfort/nginx)
+      # - echo "Copying the coverage script to the container"
+      # - docker cp community_images/nginx/bitnami/coverage_script.sh $CONTAINER_ID:/coverage_script.sh
+      # - echo "Running the script inside the container"
+      # # - docker exec $CONTAINER_ID bash /coverage_script.sh
+      # - |
+      #   if ! docker exec $CONTAINER_ID bash /coverage_script.sh; then
+      #     echo "Coverage script failed"
+      #     aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+      #                     --subject "Build Failed: NGINX Coverage Script" \
+      #                     --message "The coverage script failed to execute. Check the logs for details."
+      #     exit 1
+      #   fi
         
