updated success and failed notification

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -37,6 +37,7 @@ phases:
       - echo "Copying the coverage script to the container"
       - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
 
+
       - echo "Running the coverage script inside the container"
       - |
         if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
@@ -45,5 +46,20 @@ phases:
                           --subject "Build Failed: NGINX Coverage Script" \
                           --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
           exit 1;
+        else
+          echo "Coverage script succeeded, sending success notification with logs";
+          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+                          --subject "Build Succeeded: NGINX Coverage Script" \
+                          --message "The coverage script executed successfully. Here are the logs:\n\n$(cat /tmp/coverage_output.log)";
         fi
-        
+
+      # - echo "Running the coverage script inside the container"
+      # - |
+      #   if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
+      #     echo "Coverage script failed, sending SNS notification";
+      #     aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+      #                     --subject "Build Failed: NGINX Coverage Script" \
+      #                     --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
+      #     exit 1;
+      #   fi
+
