debug coverage script

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -37,6 +37,16 @@ phases:
       - echo "Copying the coverage script to the container"
       - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
 
+      - echo "Editing /opt/bitnami/nginx/conf/nginx.conf to replace 'user www;' with 'user daemon daemon;'"
+      # Check if the file contains 'user www;' and replace it with 'user daemon daemon;'
+      - sudo sed -i 's/user www;/user daemon daemon;/g' /opt/bitnami/nginx/conf/nginx.conf
+      # Verify that the replacement has been made
+      - grep 'user daemon daemon;' /opt/bitnami/nginx/conf/nginx.conf && echo "Replacement successful"
+
+      - echo "Starting post-build phase"
+      - sudo nginx -t  # Test the Nginx configuration
+      - sudo /opt/bitnami/scripts/nginx/reload.sh
+
       # - echo "Running the coverage script inside the container"
       # - |
       #   if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
@@ -47,20 +57,23 @@ phases:
       #     exit 1;
       #   fi
       
-      - echo "Running the coverage script inside the container"
-      - |
-        if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
-          # If the coverage script fails
-          echo "Coverage script failed, sending SNS failure notification";
-          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
-                          --subject "Build Failed: NGINX Coverage Script" \
-                          --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
-          exit 1;  # Ensure the build fails
-        else
-          # If the coverage script succeeds
-          echo "Coverage script succeeded, sending SNS success notification";
-          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
-                          --subject "Build Succeeded: NGINX Coverage Script" \
-                          --message "The coverage script executed successfully. Here are the logs:\n\n$(cat /tmp/coverage_output.log)";
-        fi
+
+      
+      # - echo "Running the coverage script inside the container"
+      # - |
+      #   if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
+      #     # If the coverage script fails
+      #     echo "Coverage script failed, sending SNS failure notification";
+
+      #     aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+      #                     --subject "Build Failed: NGINX Coverage Script" \
+      #                     --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
+      #     exit 1;  # Ensure the build fails
+      #   else
+      #     # If the coverage script succeeds
+      #     echo "Coverage script succeeded, sending SNS success notification";
+      #     aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+      #                     --subject "Build Succeeded: NGINX Coverage Script" \
+      #                     --message "The coverage script executed successfully. Here are the logs:\n\n$(cat /tmp/coverage_output.log)";
+      #   fi
 
