updated

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -31,20 +31,15 @@ phases:
   post_build:
     commands:
 
-      - echo "Checking the status of running containers"
-      - docker ps -a
-      - echo "Finding the container ID for bitnami-nginx-1"
+      - echo "Running coverage script in the container"
       - CONTAINER_ID=$(docker ps -qf "name=bitnami-nginx-1")
-      - echo "Container ID for bitnami-nginx-1 is $CONTAINER_ID"
-      - echo "Copying the coverage script to the container"
-      - ls && pwd
       - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
-      - echo "Running the coverage script inside the container"
+      - docker exec -it $CONTAINER_ID sh -c "chmod +x /coverage_script.sh"
       - |
-        if ! docker exec $CONTAINER_ID bash /coverage_script.sh; then
-          echo "Run Coverage script ";
+        docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1 || {
+          echo "Coverage script failed";
           aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
                           --subject "Build Failed: NGINX Coverage Script" \
-                          --message "The coverage script failed to execute. Check the logs for details.";
+                          --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
           exit 1;
-        fi
+        }
