debug coverage script

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -37,23 +37,23 @@ phases:
       - echo "Copying the coverage script to the container"
       - docker cp coverage_script.sh $CONTAINER_ID:/coverage_script.sh
 
-      - echo "Checking if nginx.conf exists"
-      - if [ -f /opt/bitnami/nginx/conf/nginx.conf ]; then sudo sed -i 's/user www;/user daemon daemon;/g' /opt/bitnami/nginx/conf/nginx.conf; else echo "nginx.conf not found, skipping"; fi
-      - echo "Proceeding with other steps"
+      # - echo "Checking if nginx.conf exists"
+      # - if [ -f /opt/bitnami/nginx/conf/nginx.conf ]; then sudo sed -i 's/user www;/user daemon daemon;/g' /opt/bitnami/nginx/conf/nginx.conf; else echo "nginx.conf not found, skipping"; fi
+      # - echo "Proceeding with other steps"
 
-      - echo "Starting post-build phase"
-      - sudo nginx -t  # Test the Nginx configuration
-      - sudo /opt/bitnami/scripts/nginx/reload.sh
+      # - echo "Starting post-build phase"
+      # - sudo nginx -t  # Test the Nginx configuration
+      # - sudo /opt/bitnami/scripts/nginx/reload.sh
 
-      # - echo "Running the coverage script inside the container"
-      # - |
-      #   if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
-      #     echo "Coverage script failed, sending SNS notification";
-      #     aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
-      #                     --subject "Build Failed: NGINX Coverage Script" \
-      #                     --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
-      #     exit 1;
-      #   fi
+      - echo "Running the coverage script inside the container"
+      - |
+        if ! docker exec $CONTAINER_ID bash /coverage_script.sh > /tmp/coverage_output.log 2>&1; then
+          echo "Coverage script failed, sending SNS notification";
+          aws sns publish --topic-arn "arn:aws:sns:us-east-1:550843840101:rapidfort" \
+                          --subject "Build Failed: NGINX Coverage Script" \
+                          --message "The coverage script failed to execute. Check the logs for details.\n\n$(cat /tmp/coverage_output.log)";
+          exit 1;
+        fi
       
 
       
